if(2==2){
    console.log("Yes");
}else{
    console.log("galt ");
}




if(0==null){  // this is false
    console.log("Yes");
}else{
    console.log("galt ");
}


 
if(0==""){   // 0 is equal to blank string
    console.log("yes");
}else{
    console.log("galt ");
}



if(0==undefined){
    console.log("Yes");
}else{
    console.log("galt ");
}









if(0==" "){   // ab bhi equal hi hain jb tk koi na likhe .... whitespace ko equally 0 lega kitna bhi space ho
    console.log("Yes");
}else{
    console.log("galt ");
}




if (0 == " \0") {
    console.log("yes");
} else {
    console.log("galt ");
}




var a = true;       // true means 1 and false equallent to 0

if (a == 1 ){
    console.log("yes");

} else {
    console.log("no");
}




if (1 ){
    console.log("yes");

} else {
    console.log("no");
}




if ("two "){       // true ==0 , but all rather than all are true 
    console.log("yes");

} else {
    console.log("no");
}



if (null) {  // is false
    console.log("true");
} else {
    console.log("false")
}

if (undefined) {  // is false
    console.log("true");
} else {
    console.log("false")
}



var a = true;   

if (a = 7 ){  // true kuki 7 is non zero number
    console.log("yes");

} else {
    console.log("no");
}


